workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.rork.smart-ai-assistant-slxh0fb
      vars:
        BUNDLE_ID: "app.rork.smart-ai-assistant-slxh0fb"
        APP_NAME: "Smart AI Assistant"
        MODEL_VARIANT: "int4"
      node: 20
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Download CoreML model
        script: |
          python3 -m pip install --user huggingface_hub
          export PATH="$HOME/.local/bin:$PATH"
          ./scripts/workflow.sh --variant "$MODEL_VARIANT" --step model

      - name: Expo prebuild
        script: |
          npx expo prebuild --platform ios --non-interactive --no-install

      - name: Install CocoaPods
        script: |
          cd ios && pod install --repo-update

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/SmartAIAssistant/Info.plist
          if [ -f "$PLIST" ]; then
            /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST" 2>/dev/null || true
          fi

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID" 2>/dev/null || echo "0")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Set up code signing
        script: |
          xcode-project use-profiles --warn-only

      - name: Build IPA
        script: |
          WORKSPACE="$(find ios -maxdepth 1 -name '*.xcworkspace' -type d -print | head -n 1)"
          SCHEME="$(xcodebuild -list -json -workspace "$WORKSPACE" 2>/dev/null | ruby -e 'require "json"; puts JSON.parse(STDIN.read).dig("workspace","schemes")&.first')"
          xcode-project build-ipa \
            --workspace "$WORKSPACE" \
            --scheme "$SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
