#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Submit an iOS .ipa directly to App Store Connect without EAS Submit.

Usage:
  ./scripts/submit-ios-ipa-without-eas.sh --ipa <path> [--apple-id <email>] [--app-password <app-specific-password>]
  ./scripts/submit-ios-ipa-without-eas.sh --ipa <path> --api-key <key-id> --api-issuer <issuer-id>

Authentication options:
  1) Apple ID + app-specific password
     - flags: --apple-id, --app-password
     - env fallback: APPLE_ID, APP_SPECIFIC_PASSWORD

  2) App Store Connect API key (JWT generated by altool)
     - flags: --api-key, --api-issuer
     - env fallback: APPSTORE_CONNECT_API_KEY_ID, APPSTORE_CONNECT_API_ISSUER_ID

Examples:
  ./scripts/submit-ios-ipa-without-eas.sh --ipa ./build.ipa --apple-id dev@example.com --app-password xxxx-xxxx-xxxx-xxxx

  APPSTORE_CONNECT_API_KEY_ID=ABC123DEF4 \
  APPSTORE_CONNECT_API_ISSUER_ID=11111111-2222-3333-4444-555555555555 \
  ./scripts/submit-ios-ipa-without-eas.sh --ipa ./build.ipa
USAGE
}

IPA_PATH=""
APPLE_ID="${APPLE_ID:-}"
APP_PASSWORD="${APP_SPECIFIC_PASSWORD:-}"
API_KEY="${APPSTORE_CONNECT_API_KEY_ID:-}"
API_ISSUER="${APPSTORE_CONNECT_API_ISSUER_ID:-}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ipa)
      IPA_PATH="${2:-}"
      shift 2
      ;;
    --apple-id)
      APPLE_ID="${2:-}"
      shift 2
      ;;
    --app-password)
      APP_PASSWORD="${2:-}"
      shift 2
      ;;
    --api-key)
      API_KEY="${2:-}"
      shift 2
      ;;
    --api-issuer)
      API_ISSUER="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "❌ Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$IPA_PATH" ]]; then
  echo "❌ Missing required flag: --ipa <path>" >&2
  usage
  exit 1
fi

if [[ ! -f "$IPA_PATH" ]]; then
  echo "❌ IPA file not found: $IPA_PATH" >&2
  exit 1
fi

if ! command -v xcrun >/dev/null 2>&1; then
  echo "❌ xcrun is required. Install Xcode command line tools." >&2
  exit 1
fi

ALTOOL=(xcrun altool)
if ! "${ALTOOL[@]}" --help >/dev/null 2>&1; then
  echo "❌ xcrun altool is unavailable. Install full Xcode (or switch to Transporter GUI)." >&2
  exit 1
fi

use_api_key="0"
use_apple_id="0"

if [[ -n "$API_KEY" || -n "$API_ISSUER" ]]; then
  if [[ -z "$API_KEY" || -z "$API_ISSUER" ]]; then
    echo "❌ API key auth requires both --api-key and --api-issuer." >&2
    exit 1
  fi
  use_api_key="1"
fi

if [[ -n "$APPLE_ID" || -n "$APP_PASSWORD" ]]; then
  if [[ -z "$APPLE_ID" || -z "$APP_PASSWORD" ]]; then
    echo "❌ Apple ID auth requires both --apple-id and --app-password." >&2
    exit 1
  fi
  use_apple_id="1"
fi

if [[ "$use_api_key" == "1" && "$use_apple_id" == "1" ]]; then
  echo "❌ Provide either API key auth OR Apple ID auth, not both." >&2
  exit 1
fi

if [[ "$use_api_key" == "0" && "$use_apple_id" == "0" ]]; then
  echo "❌ No authentication provided." >&2
  echo "   Use --apple-id/--app-password or --api-key/--api-issuer." >&2
  exit 1
fi

echo "[i] Validating IPA at: $IPA_PATH"

if [[ "$use_api_key" == "1" ]]; then
  echo "[i] Submitting with App Store Connect API key: $API_KEY"
  "${ALTOOL[@]}" \
    --upload-app \
    --type ios \
    --file "$IPA_PATH" \
    --apiKey "$API_KEY" \
    --apiIssuer "$API_ISSUER" \
    --verbose
else
  echo "[i] Submitting with Apple ID: $APPLE_ID"
  "${ALTOOL[@]}" \
    --upload-app \
    --type ios \
    --file "$IPA_PATH" \
    --username "$APPLE_ID" \
    --password "$APP_PASSWORD" \
    --verbose
fi

echo "✅ Upload request accepted by App Store Connect."
echo "   Check App Store Connect > TestFlight for processing status."
